### PR TITLE
Developer environment tools rework

### PR DESCRIPTION
**Pull request by rthallisey**
Make the developer env setup a little more robust to support multiple clusters, openshift and kubernetes, and make the tool extensible.

### CODE REVIEW

**Comment by rthallisey** [comment]
One thing I have to fix is the connection from asbcli to the router.  Currently the router's address is not reachable because xxx.<hostname> is not resolving.

**Comment by rthallisey** [comment]
I haven't written any docs for this yet, but to test run ```setup-cluster.sh```.  It wraps the vagrant command so we can add support for a variety of developer environments.

**Comment by jmrodri** [comment]
Like I saw in irc. running `vagrant up` will hang on updating `/etc/hosts`. Trying script as suggested now.

**Comment by jmrodri** [comment]
```
ERROR! the playbook: /home/devel/jesusr/dev/cap/origin-multinode-vagrant/openshift-ansible/playbooks/byo/config.yml could not be found
```

Maybe because I don't have openshift ansible checked out:

 `ansible-playbook "${OPENSHIFT_ANSIBLE_DIR}/playbooks/byo/config.yml" --sudo`

**Comment by rthallisey** [comment]
The expectation is you will have openshift-ansible or the coresponding kubernetes playbook in your local dir.  I don't have any validations and docs just yet so it's still a little rough.

**Comment by rthallisey** [comment]
@dymurray Added the ability to use cached vagrant boxes.  I tested it with your 1.5.0-rc boxes, but the nodes fail to come up because they have the save ip addresses.  Maybe vagrant has a way around that...

**Comment by rthallisey** [comment]
@dymurray Latest patch works with 1.5.0-rc images. Next up I'll write a doc.

**Pull request closed without merging**
